{% set name = "presidio_evaluator" %}
{% set version = "0.22" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/microsoft/presidio-research/archive/refs/tags/{{ version }}.tar.gz
  sha256: f6af71b4d2c89b3ef68c31c000695ec809d62cea70f6fe88d1d453b984ebba1b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry-core
  run:
    - python >={{ python_min }},<4
    - spacy >=3.8.0,<4
    - pandas >=2.1.4,<3
    - tqdm >=4.60.0,<5
    - faker >=21.0,<22
    - scikit-learn >=1.3.2.12,<2
    - xmltodict >=0.12.0,<0.13
    - presidio-analyzer >=2.2.351,<3
    - presidio-anonymizer >=2.2.351,<3
    - requests >=2.25,<3
    - python-dotenv >=1.0.0,<2
    - plotly >=5.24.0,<6
  run_constrained: # Optional packages
    - azure-ai-textanalytics
    - flair >=0.14.0,<0.15
    - spacy_stanza >=1.0.0,<2
    - spacy_huggingface_pipelines >=0.0.4,<0.0.5

test:
  imports:
    - presidio_evaluator
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip list
    - pip check

about:
  home: https://github.com/microsoft/presidio
  summary: 'Presidio Evaluator package'
  description: |
    Presidio Evaluator package.
  license: MIT
  license_file: LICENSE
  doc_url: https://microsoft.github.io/presidio
  dev_url: https://github.com/microsoft/presidio

extra:
  recipe-maintainers:
    - julcsii
    - heckert
